<a href="https://colab.research.google.com/github/Rakesh-584/Numpy/blob/main/numpy_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy
- Short for Numerical Python
- Foundational Package for Numerical computing in python
- Provides an ndarray object which is an efficient multidimensional array providing fast array oriented operations
- Provides a lot of functions

In [ ]:
import numpy as np

In [ ]:
import time

## Calculating the square of each element

In [ ]:
# using lists
arr_list = [i for i in range(1,10000000,1)]

In [ ]:
arr_list[:10]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
start_time = time.time()
sq_arr = [x**2 for x in arr_list]
end_time = time.time()

print("time taken using lists", end_time - start_time)

time taken using lists 1.3391354084014893


In [ ]:
sq_arr[:10]

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [ ]:
# using Numpy array
arr_numpy = np.arange(1,10000000,1)


In [ ]:
arr_numpy[:10]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
start_time = time.time()
sq_numpy = arr_numpy**2
end_time = time.time()

print("time taken using numpy", end_time - start_time)

time taken using numpy 0.03835010528564453


# Creating ndarrays

##### Creating ndarray from an object

In [ ]:
l1 = [1,2,3,4,5]
a1 = np.array(l1)
a1

array([1, 2, 3, 4, 5])

In [ ]:
type(a1)

numpy.ndarray

In [ ]:
t1 = (1,2,3,4,5)
a1 = np.array(t1)
a1

array([1, 2, 3, 4, 5])

In [ ]:
a1 = np.array(range(1,11))
a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
a1.shape

(10,)

In [ ]:
a1.dtype

dtype('int64')

In [ ]:
a1.ndim

1

In [ ]:
a1 = np.array([[1,2,3],
               [4,5,6]])
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a1.shape

(2, 3)

In [ ]:
a1.ndim

2

In [ ]:
a1 = np.array([[[1,2],[3,4]],
               [[5,6], [7,8]]])
a1

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
a1.shape

(2, 2, 2)

In [ ]:
a1.ndim

3

In [ ]:
a = np.array([1,2,3,4,5], dtype = float)
a

array([1., 2., 3., 4., 5.])

In [ ]:
a.dtype

dtype('float64')

In [ ]:
a = np.array([1.5,2.6,3.1,4.8,5.2], dtype = int)
a

array([1, 2, 3, 4, 5])

In [ ]:
a.dtype

dtype('int64')

### Typecasting ndarrays

In [ ]:
a = np.array([1,2,3,4,5])
a


array([1, 2, 3, 4, 5])

In [ ]:
a = a.astype(float)
a

array([1., 2., 3., 4., 5.])

In [ ]:
a = a.astype(int)
a

array([1, 2, 3, 4, 5])

In [ ]:
a = a.astype(str)
a

array(['1', '2', '3', '4', '5'], dtype='<U21')

In [ ]:
a.dtype

dtype('<U21')

### Creating ndarrays by specifying a range

In [ ]:
a1 = np.arange(0,10)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a1 = np.arange(0,21,2)
a1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
a1 = np.arange(10)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a1 = np.arange(10, dtype = float)
a1

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

### Creating ndarrays of ones

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.ones((3,2,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [ ]:
np.ones((5,5), dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

### Creating ndarray of zeros

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### Creating ndarray of a specific value

In [ ]:
np.full((4,5), fill_value = 6)

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

### Creating an identity matrix

In [ ]:
np.eye(3)   # Identity matrix is a square matrix where elements of the principal diagonal are 1 and others 0

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Operations on ndarrays

In [ ]:
l = [1,2,3,4,5,6]

a1 = np.array(l)
a1

array([1, 2, 3, 4, 5, 6])

In [ ]:
# list
l2 = [ele + 3 for ele in l]
l2

[4, 5, 6, 7, 8, 9]

In [ ]:
# Numpy
temp = a1 + 3


In [ ]:
a2 = np.array([4,5,6,7,8,9])
a2

array([4, 5, 6, 7, 8, 9])

In [ ]:
a1 + a2

array([ 5,  7,  9, 11, 13, 15])

In [ ]:
a1 + [2,3,4,5,6,7]

array([ 3,  5,  7,  9, 11, 13])

In [ ]:
a1 * 2

array([ 2,  4,  6,  8, 10, 12])

In [ ]:
temp - 3

array([1, 2, 3, 4, 5, 6])

In [ ]:
print(a1)
print(a2)

[1 2 3 4 5 6]
[4 5 6 7 8 9]


In [ ]:
a1 * a2

array([ 4, 10, 18, 28, 40, 54])

In [ ]:
a1 = np.array([2,4,6,8,10])
a3 = a1 / 2
a3

array([1., 2., 3., 4., 5.])

In [ ]:
a1 // 2

array([1, 2, 3, 4, 5])

In [ ]:
a1 % 3

array([2, 1, 0, 2, 1])

In [ ]:
a1 ** 2

array([  4,  16,  36,  64, 100])

In [ ]:
a2 = np.array([2,3,4,5,6])
a1 ** a2

array([      4,      64,    1296,   32768, 1000000])

In [ ]:
a1

array([ 2,  4,  6,  8, 10])

In [ ]:
2 / a1

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ])

In [ ]:
l1 = np.array([1,2,3,4,5,6])
l1 < 4


array([ True,  True,  True, False, False, False])

In [ ]:
a1 = np.array([1,2,3,4,5,6])
a1 < 4

array([ True,  True,  True, False, False, False])

In [ ]:
# list
l1 = [9,1,4,5,3,6]
l2 = [7,4,2,1,6,7]

l1 < l2

False

In [ ]:
a1 = np.array([2,1,4,5,3,6])
a2 = np.array([3,4,2,1,6,6])

In [ ]:
a1 < a2

array([ True,  True, False, False,  True, False])

In [ ]:
a1 > a2

array([False, False,  True,  True, False, False])

In [ ]:
a1 <= a2

array([ True,  True, False, False,  True,  True])

In [ ]:
a1 >= a2

array([False, False,  True,  True, False, False])

In [ ]:
a1 == a2

array([False, False, False, False, False,  True])

In [ ]:
# Operation between two ndarrays not possible if shapes are not same
a1 = np.array([1,2,3,4,5])
a2 = np.array([2,3,4,5,6,])

print(a1 + a2)

[ 3  5  7  9 11]


## Indexing and Slicing ndarrays

In [ ]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a[0]

np.int64(0)

In [ ]:
a[1]

np.int64(1)

In [ ]:
a[6]

np.int64(6)

In [ ]:
a[-1]

np.int64(9)

In [ ]:
a[-2]

np.int64(8)

In [ ]:
a[0:8]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
a[0:8:2]

array([0, 2, 4, 6])

In [ ]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a[-8:-3]

array([2, 3, 4, 5, 6])

In [ ]:
a[-1:2:-2]

array([9, 7, 5, 3])

## Reshape and Transpose

In [ ]:
a = np.arange(16)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
a.shape

(10,)

In [ ]:
a.ndim

1

In [ ]:
a=np.arange(16)
a = a.reshape((16,1))
print(a)

[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]]


In [ ]:
a.shape

(16, 1)

In [ ]:
a.ndim

2

In [ ]:
a = a.reshape((1,16))
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [ ]:
a.shape

(1, 16)

In [ ]:
a.ndim

2

In [ ]:
a.reshape((4,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
a.reshape((2,2,4))

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [ ]:
a = np.arange(36)

a.reshape(1,36)
a.reshape(2,18)
a.reshape(3,12)
a.reshape(4,9)
a.reshape(6,6)
a.reshape(9,4)
a.reshape(12,3)
a.reshape(18,2)
a.reshape(36,1)

print('Possible 2D shape : ', 9)

Possible 2D shape :  9


In [ ]:
a = np.arange(16).reshape((4,4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
a.T # Transpose

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])