<a href="https://colab.research.google.com/github/Rakesh-584/Numpy/blob/main/numpy_functions__conditional_indexing_and_slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Functions

In [ ]:
a = np.array([2,4,3,6,5,8,7,9,1,0])
a

array([2, 4, 3, 6, 5, 8, 7, 9, 1, 0])

In [ ]:
a.sort()
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
s = np.square(a)
s

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
np.sqrt(s)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
np.sqrt(16)

np.float64(4.0)

In [ ]:
np.sqrt([4,9])

array([2., 3.])

In [ ]:
a = np.array([8,27,64])
np.cbrt(a)

array([2., 3., 4.])

In [ ]:
np.abs([-1,2,3,-5,-6,-2,6])

array([1, 2, 3, 5, 6, 2, 6])

In [ ]:
abs(-8)

8

In [ ]:
np.add([1,2,3],[4,5,6])

array([5, 7, 9])

In [ ]:
np.subtract([4,5,6],[1,2,3])

array([3, 3, 3])

In [ ]:
np.multiply([1,2,3],[2,3,4])

array([ 2,  6, 12])

In [ ]:
a1 = np.array([2,1,4,5,3,6])
a2 = np.array([3,4,2,1,6,5])

In [ ]:
np.maximum(a1,a2)

array([3, 4, 4, 5, 6, 6])

In [ ]:
np.minimum(a1,a2)

array([2, 1, 2, 1, 3, 5])

In [ ]:
a1 > a2

array([False, False,  True,  True, False,  True])

In [ ]:
np.greater(a1,a2)

array([False, False,  True,  True, False,  True])

In [ ]:
np.less(a1,a2)

array([ True,  True, False, False,  True, False])

In [ ]:
a1 = np.arange(21)
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [ ]:
np.mean(a1)

10.0

In [ ]:
np.mean([1,2,3,4,5,6,7,8,9])

5.0

In [ ]:
np.var([1,2,3,4,5,6,7,8,9])

np.float64(6.666666666666667)

In [ ]:
np.std([1,2,3,4,5,6,7,8,9])

np.float64(2.581988897471611)

In [ ]:
np.median(a1)

np.float64(3.5)

In [ ]:
a1.mean()

np.float64(3.5)

In [ ]:
a1.var()

np.float64(2.9166666666666665)

In [ ]:
a1.std()

np.float64(1.707825127659933)

In [ ]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
a.cumsum()

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55])

In [ ]:
a.cumprod()

array([      1,       2,       6,      24,     120,     720,    5040,
         40320,  362880, 3628800])

In [ ]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
a.min()

np.int64(1)

In [ ]:
a.max()

np.int64(10)

In [ ]:
a.sum()

np.int64(55)

In [ ]:
a = np.arange(64).reshape(8,8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [ ]:
a.shape

(8, 8)

In [ ]:
a.mean()

np.float64(31.5)

In [ ]:
a.mean(axis = 0) # column wise avg

array([28., 29., 30., 31., 32., 33., 34., 35.])

In [ ]:
a.mean(axis = 1) # row wise avg

array([ 3.5, 11.5, 19.5, 27.5, 35.5, 43.5, 51.5, 59.5])

In [ ]:
a.std()

np.float64(18.472953201911167)

In [ ]:
a.std(axis = 0)

array([18.33030278, 18.33030278, 18.33030278, 18.33030278, 18.33030278,
       18.33030278, 18.33030278, 18.33030278])

In [ ]:
a.std(axis = 1)

array([2.29128785, 2.29128785, 2.29128785, 2.29128785, 2.29128785,
       2.29128785, 2.29128785, 2.29128785])

In [ ]:
a.max()

np.int64(63)

In [ ]:
a.max(axis = 0)

array([56, 57, 58, 59, 60, 61, 62, 63])

In [ ]:
a.max(axis = 1)

array([ 7, 15, 23, 31, 39, 47, 55, 63])

In [ ]:
x = np.array([10,30,80,20,40])
x

array([10, 30, 80, 20, 40])

In [ ]:
np.argmax(x)             # returns the index of maximum element

np.int64(2)

In [ ]:
np.argmin(x)             # returns the index of minimum element

np.int64(0)

In [ ]:
a1 = np.array([2,1,5,4,3,5,6,7,3,10,2,3]).reshape(3,4)
a1

array([[ 2,  1,  5,  4],
       [ 3,  5,  6,  7],
       [ 3, 10,  2,  3]])

In [ ]:
np.argmax(a1)

np.int64(9)

In [ ]:
np.argmax(a1, axis = 0)

array([1, 2, 1, 1])

In [ ]:
np.argmax(a1, axis = 1)

array([2, 3, 1])

In [ ]:
np.argmin(a1, axis = 0)

array([0, 0, 2, 2])

In [ ]:
np.argmin(a1, axis = 1)

array([1, 0, 2])

In [ ]:
a1

array([[ 2,  1,  5,  4],
       [ 3,  5,  6,  7],
       [ 3, 10,  2,  3]])

In [ ]:
a1.ravel()         # Converts to single dimension

array([2, 1, 4, 5, 3, 6])

In [ ]:
a2 = a1.reshape(1,12)
a2

array([[ 2,  1,  5,  4,  3,  5,  6,  7,  3, 10,  2,  3]])

In [ ]:
a2.ndim

1

In [ ]:
a2.shape

(6,)

In [ ]:
a2 = a2.squeeze()
a2

array([3, 4, 2, 1, 6, 5])

In [ ]:
a2.shape

(6,)

In [ ]:
a2 = a2.reshape(3,4,1)
a2

array([[[ 2],
        [ 1],
        [ 5],
        [ 4]],

       [[ 3],
        [ 5],
        [ 6],
        [ 7]],

       [[ 3],
        [10],
        [ 2],
        [ 3]]])

In [ ]:
a2 = a2.squeeze()
a2

array([[ 2,  1,  5,  4],
       [ 3,  5,  6,  7],
       [ 3, 10,  2,  3]])

In [ ]:
a2.shape

(3, 4)

In [ ]:
np.linspace(1,10, 100)

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

In [ ]:
a = np.empty((2,3), dtype = int)
a

array([[4612248968380809216, 4618722892845154304, 4598175219545276416],
       [4612248968380809216, 4598175219545276416, 4618722892845154304]])

### Concatenation

In [ ]:
a1 = np.arange(5)
a2 = np.arange(5,10)

In [ ]:
np.concatenate((a1,a2))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a1 = np.arange(12).reshape(4,3)
a2 = np.arange(12,24).reshape(4,3)
print(a1)
print(a2)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


In [ ]:
np.concatenate((a1,a2))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [ ]:
np.concatenate((a1,a2), axis = 0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [ ]:
np.concatenate((a1,a2), axis = 1)

array([[ 0,  1,  2, 12, 13, 14],
       [ 3,  4,  5, 15, 16, 17],
       [ 6,  7,  8, 18, 19, 20],
       [ 9, 10, 11, 21, 22, 23]])

In [ ]:
a1 = a
a2 = a.T
print(a1)
print()
print(a2)

[[4612248968380809216 4618722892845154304 4598175219545276416]
 [4612248968380809216 4598175219545276416 4618722892845154304]]

[[4612248968380809216 4612248968380809216]
 [4618722892845154304 4598175219545276416]
 [4598175219545276416 4618722892845154304]]


In [ ]:
np.concatenate((a1,a2.T), axis = 0)

array([[4612248968380809216, 4618722892845154304, 4598175219545276416],
       [4612248968380809216, 4598175219545276416, 4618722892845154304],
       [4612248968380809216, 4618722892845154304, 4598175219545276416],
       [4612248968380809216, 4598175219545276416, 4618722892845154304]])

In [ ]:
np.concatenate((a1,a2.T), axis = 1)

array([[4612248968380809216, 4618722892845154304, 4598175219545276416,
        4612248968380809216, 4618722892845154304, 4598175219545276416],
       [4612248968380809216, 4598175219545276416, 4618722892845154304,
        4612248968380809216, 4598175219545276416, 4618722892845154304]])

## Random numbers

In [ ]:
np.random.randint(1,10)

9

In [ ]:
np.random.randint(50)

5

In [ ]:
np.random.randint(1,100,10)

array([23, 48, 96, 36, 29,  6,  7, 26, 77, 47])

In [ ]:
np.random.randint(11,100,(10,10))

array([[62, 97, 71, 21, 18, 58, 41, 49, 80, 99],
       [20, 28, 13, 79, 49, 27, 81, 59, 66, 30],
       [30, 21, 98, 65, 77, 33, 29, 23, 58, 38],
       [86, 69, 84, 83, 66, 17, 92, 97, 85, 59],
       [46, 87, 72, 16, 55, 60, 67, 99, 98, 13],
       [55, 32, 56, 52, 91, 34, 42, 51, 58, 43],
       [69, 55, 93, 37, 55, 40, 88, 21, 94, 64],
       [55, 45, 78, 31, 11, 14, 81, 30, 12, 85],
       [79, 16, 76, 66, 74, 73, 62, 75, 91, 28],
       [96, 59, 55, 51, 46, 53, 15, 23, 13, 45]])

In [ ]:
np.random.rand(10)

array([0.38255062, 0.6481503 , 0.28545357, 0.58272093, 0.26594406,
       0.45605528, 0.06891394, 0.74192375, 0.09384193, 0.04853921])

In [ ]:
np.random.randn(10)

array([ 0.02107289,  0.21256418, -0.33897932, -0.11225784, -0.89212729,
       -0.76103084, -0.82866453,  1.66800707, -1.40318248, -0.48663233])

In [ ]:
np.random.randn(3,4)

array([[ 0.66177453, -0.58276759, -1.07934516,  0.63970537],
       [ 0.43339694, -1.05166161,  0.03324606,  0.31137631],
       [ 0.37452473,  0.45674494, -0.51523592,  0.04067083]])

# Conditional Indexing

In [ ]:
a = np.random.randint(11,100,(8,8))
a

array([[73, 36, 49, 62, 76, 14, 90, 33],
       [19, 69, 16, 26, 32, 77, 59, 16],
       [88, 37, 71, 62, 20, 72, 89, 76],
       [17, 73, 50, 18, 85, 34, 69, 77],
       [59, 11, 70, 51, 94, 20, 96, 16],
       [38, 14, 67, 85, 58, 20, 85, 33],
       [54, 92, 52, 99, 75, 18, 38, 97],
       [54, 99, 58, 52, 86, 43, 87, 84]])

In [ ]:
a > 50

array([[ True, False, False,  True,  True, False,  True, False],
       [False,  True, False, False, False,  True,  True, False],
       [ True, False,  True,  True, False,  True,  True,  True],
       [False,  True, False, False,  True, False,  True,  True],
       [ True, False,  True,  True,  True, False,  True, False],
       [False, False,  True,  True,  True, False,  True, False],
       [ True,  True,  True,  True,  True, False, False,  True],
       [ True,  True,  True,  True,  True, False,  True,  True]])

In [ ]:
a[a > 50]

array([73, 62, 76, 90, 69, 77, 59, 88, 71, 62, 72, 89, 76, 73, 85, 69, 77,
       59, 70, 51, 94, 96, 67, 85, 58, 85, 54, 92, 52, 99, 75, 97, 54, 99,
       58, 52, 86, 87, 84])

In [ ]:
a[a < 50]

array([36, 49, 14, 33, 19, 16, 26, 32, 16, 37, 20, 17, 18, 34, 11, 20, 16,
       38, 14, 20, 33, 18, 38, 43])

In [ ]:
a[a <= 40]

array([36, 14, 33, 19, 16, 26, 32, 16, 37, 20, 17, 18, 34, 11, 20, 16, 38,
       14, 20, 33, 18, 38])

In [ ]:
a[a == 16]

array([16, 16, 16])

# Slicing in Multidimensional Arrays

In [ ]:
a = np.random.randint(10,100,(12,12))
a

array([[25, 55, 49, 16, 85, 71, 83, 53, 80, 21, 75, 11],
       [66, 98, 72, 23, 88, 86, 28, 29, 92, 58, 81, 46],
       [48, 92, 72, 28, 64, 47, 93, 61, 95, 67, 89, 53],
       [96, 62, 47, 33, 92, 95, 41, 45, 96, 82, 29, 85],
       [51, 66, 19, 81, 80, 42, 76, 51, 33, 38, 88, 17],
       [58, 65, 10, 11, 63, 79, 84, 71, 99, 31, 52, 77],
       [78, 11, 15, 90, 59, 80, 31, 41, 63, 88, 77, 83],
       [22, 36, 75, 65, 14, 28, 54, 78, 61, 37, 80, 69],
       [63, 27, 37, 92, 50, 39, 63, 60, 51, 91, 90, 46],
       [92, 20, 38, 19, 43, 53, 97, 38, 72, 11, 98, 47],
       [75, 10, 61, 17, 59, 18, 89, 67, 82, 66, 56, 46],
       [30, 51, 83, 91, 83, 33, 58, 91, 92, 44, 77, 68]])

In [ ]:
a[0:5]

array([[25, 55, 49, 16, 85, 71, 83, 53, 80, 21, 75, 11],
       [66, 98, 72, 23, 88, 86, 28, 29, 92, 58, 81, 46],
       [48, 92, 72, 28, 64, 47, 93, 61, 95, 67, 89, 53],
       [96, 62, 47, 33, 92, 95, 41, 45, 96, 82, 29, 85],
       [51, 66, 19, 81, 80, 42, 76, 51, 33, 38, 88, 17]])

In [ ]:
a[6:11]

array([[78, 11, 15, 90, 59, 80, 31, 41, 63, 88, 77, 83],
       [22, 36, 75, 65, 14, 28, 54, 78, 61, 37, 80, 69],
       [63, 27, 37, 92, 50, 39, 63, 60, 51, 91, 90, 46],
       [92, 20, 38, 19, 43, 53, 97, 38, 72, 11, 98, 47],
       [75, 10, 61, 17, 59, 18, 89, 67, 82, 66, 56, 46]])

In [ ]:
a[-6:-1]

array([[78, 11, 15, 90, 59, 80, 31, 41, 63, 88, 77, 83],
       [22, 36, 75, 65, 14, 28, 54, 78, 61, 37, 80, 69],
       [63, 27, 37, 92, 50, 39, 63, 60, 51, 91, 90, 46],
       [92, 20, 38, 19, 43, 53, 97, 38, 72, 11, 98, 47],
       [75, 10, 61, 17, 59, 18, 89, 67, 82, 66, 56, 46]])

In [ ]:
a[0:6,0:4]

array([[25, 55, 49, 16],
       [66, 98, 72, 23],
       [48, 92, 72, 28],
       [96, 62, 47, 33],
       [51, 66, 19, 81],
       [58, 65, 10, 11]])

In [ ]:
a[2:9:2, 3:8:2]

array([[28, 47, 61],
       [81, 42, 51],
       [90, 80, 41],
       [92, 39, 60]])

In [ ]:
a[10:3:-1, 5:10]

array([[18, 89, 67, 82, 66],
       [53, 97, 38, 72, 11],
       [39, 63, 60, 51, 91],
       [28, 54, 78, 61, 37],
       [80, 31, 41, 63, 88],
       [79, 84, 71, 99, 31],
       [42, 76, 51, 33, 38]])

In [ ]:
# Take marks of two students in 5 subjects as input and calculate the absolute difference in marks of corresponding subjects
student1 = list(map(int, input('Enter the marks in five subjects for student 1: ').split()))
student2 = list(map(int, input('Enter the marks in five subjects for student 2: ').split()))

student1 = np.array(student1)
student2 = np.array(student2)
diff = np.abs(student1 - student2)
diff